name: flake8 Lint

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Analysing the code with flake8
      run: |
        flake8 . --tee --output-file flake8_report.txt || true
        cat flake8_report.txt # ここでレポートの内容を表示

    - name: Upload flake8 report
      uses: actions/upload-artifact@v2
      with:
        name: flake8-report
        path: flake8_report.txt
